#!/usr/bin/env bash
# a script that displays information about subdomains

# shellcheck disable=SC2086

subdomain_info () {
    domain="$1"
    subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        result=$(dig +short "$sub.$domain")
        info=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ {getline; print}')
        record_type=$(echo "$info" | awk '{print $4}')
        destination=$(echo "$info" | awk '{print $5}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

domain="$1"
subdomain="$2"

subdomain_info "$domain" "$subdomain"
