#!/usr/bin/env bash
# Script that configures Nginx server with a custom header

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

sed -i '/server_name _;/a \
        rewrite ^\/redirect_me https:\/\/github.com\/hiba-emording permanent;\n\
        error_page 404 \/custom_404.html;\n\
        location = \/custom_404.html {\n\
            root \/usr\/share\/nginx\/html;\n\
            internal;\n\
        }' /etc/nginx/sites-available/default

sed -i '/include \/etc\/nginx\/sites-enabled\/\*;/a \
        add_header X-Served-By "$HOSTNAME";' /etc/nginx/nginx.conf

service nginx start
