#!/usr/bin/env bash
# Installs and sets up HAProxy

apt-get update
apt-get install -y haproxy

if [ ! -d "/etc/haproxy" ]; then
    mkdir -p /etc/haproxy
fi

if [ ! -f "/etc/haproxy/haproxy.cfg" ]; then
    touch /etc/haproxy/haproxy.cfg
fi

cat <<EOF >> /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend load_balancer
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 35.153.57.39:80 check
    server web-02 100.26.213.23:80 check
EOF

service haproxy restart
