#!/usr/bin/env bash
# Configurations of Nginx server to listen on port 80.

if [ -e /etc/nginx/sites-enabled/default ]; then
    rm /etc/nginx/sites-enabled/default
fi

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart
