#!/usr/bin/env bash
# This script is displaying numbers from 1 to 100 in a list format:
# FizzBuzz when the number is a multiple of 3 and 5
# Fizz when the number is multiple of 3
# Buzz when the number is a multiple of 5
# Otherwise, the number

for number in {1..100}
do

if (( number % 15 == 0 ))
then
echo "FizzBuzz"

elif (( number % 3 == 0 ))
then
echo "Fizz"

elif (( number % 5 == 0 ))
then
echo "Buzz"

else
echo "$number"
fi

done
