#!/usr/bin/env bash
# This script is displaying the content of the current directory in a list format
# Only the part of the name after the first dash is displayed

list=$(ls)
for i in $list
do
echo "$i" | cut -d '-' -f2
done
